# Generated by Django 5.1.7 on 2025-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ownerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerreview',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
