# Generated by Django 5.1.7 on 2025-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boost_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='boosted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
