name: Ec2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            echo "Setting variables..."
            REPO_DIR="/home/ubuntu/new_code/knockes_backend-feature-user-management-prod/knockes_backend-feature-user-management-prod"
            BRANCH="main"
            REPO_URL="https://github.com/roboxoXd3/knockes_backend.git"

            if [ -d "$REPO_DIR/.git" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd "$REPO_DIR"
              git fetch origin "$BRANCH"
              git reset --hard origin/"$BRANCH"
              git clean -fd
            else
              echo "Repository not found. Cloning fresh..."
              rm -rf "$REPO_DIR"
              git clone -b "$BRANCH" "$REPO_URL" "$REPO_DIR"
            fi

            echo "Installing dependencies..."
            cd "$REPO_DIR"
            pip3 install --user -r requirements.txt
            echo "Running database migrations..."
            python3 manage.py migrate
            echo "Collecting static files..."
            python3 manage.py collectstatic --noinput
            echo "Restarting Gunicorn service..."
            sudo systemctl restart gunicorn
            echo "Deployment complete."
          EOF
